name:                jenkins-notifier
version:             0.1.0.0
github:              "githubuser/jenkins-notifier"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2018 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/jenkins-notifier#readme>

dependencies:
- base >= 4.7 && < 5
- lens
- aeson
- wreq
- http-client-tls
- connection
- bytestring
- text
- transformers
- mtl
- dhall

library:
  source-dirs: src

executables:
  jenkins-notifier-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - jenkins-notifier

tests:
  jenkins-notifier-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - jenkins-notifier
